import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { WindowInfoProvider } from "@faceless-ui/window-info";

import { SmoothScroll } from "./_layout/SmoothScroll";
import { Footer } from "./_layout/Footer";

import "./globals.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<SmoothScroll>
				<body className={GeistSans.className}>
					<main>{children}</main>
					<Footer />
				</body>
			</SmoothScroll>
		</html>
	);
}
