import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Providers } from "./_providers";
import { SmoothScroll } from "./_layout/SmoothScroll";
import { Footer } from "./_layout/Footer";

import "./globals.scss";
import { ComponentToolTip } from "./_components/_lib/ComponentTooltip";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Providers>
				<SmoothScroll>
					<body className={GeistSans.className}>
						<main>{children}</main>
						<Footer />
					</body>
				</SmoothScroll>
			</Providers>
		</html>
	);
}
