import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Providers } from "./_providers";
import { SmoothScroll } from "./_layout/SmoothScroll";
import { ContextMenu } from "./_components/_lib/ContextMenu";
import { Footer } from "./_layout/Footer";

import "./globals.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Providers>
				<SmoothScroll>
					<body
						className={[GeistSans.className, GeistMono.className].join(" ")}
					>
						<ContextMenu>
							<main>{children}</main>
							<Footer />
						</ContextMenu>
					</body>
				</SmoothScroll>
			</Providers>
		</html>
	);
}
